# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-06-06 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiskUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_system', models.CharField(max_length=64, verbose_name='系统文件')),
                ('disk_capacity', models.CharField(max_length=64, verbose_name='磁盘容量')),
                ('disk_used', models.CharField(max_length=64, verbose_name='磁盘已用')),
                ('disk_able', models.CharField(max_length=64, verbose_name='磁盘可用')),
                ('disk_rate', models.CharField(max_length=64, verbose_name='磁盘使用率')),
                ('disk_mount', models.CharField(max_length=64, verbose_name='挂载点')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='录入时间')),
            ],
        ),
    ]
