# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-06-14 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0003_auto_20190606_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='diskusage',
            name='disk',
            field=models.CharField(default='/usr/', max_length=16),
        ),
        migrations.AddField(
            model_name='diskusage',
            name='ip',
            field=models.CharField(default='10.0.1.80', max_length=32, verbose_name='ip地址'),
        ),
        migrations.AddField(
            model_name='diskusage',
            name='system',
            field=models.CharField(default='linux', max_length=16),
        ),
    ]
