# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-06-16 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0006_auto_20190615_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiskUsages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default='10.0.1.80', max_length=32, verbose_name='ip地址')),
                ('system', models.CharField(default='linux', max_length=16, verbose_name='系统')),
                ('disk', models.CharField(default='usr', max_length=16, verbose_name='磁盘')),
                ('file_system', models.CharField(max_length=64, verbose_name='系统文件')),
                ('disk_capacity', models.CharField(max_length=64, verbose_name='磁盘容量')),
                ('disk_used', models.CharField(max_length=64, verbose_name='磁盘已用')),
                ('disk_able', models.CharField(max_length=64, verbose_name='磁盘可用')),
                ('disk_rate', models.CharField(max_length=64, verbose_name='磁盘使用率')),
                ('disk_mount', models.CharField(max_length=64, verbose_name='挂载点')),
                ('add_time', models.DateTimeField(auto_now=True, max_length=0, verbose_name='录入时间')),
            ],
        ),
        migrations.DeleteModel(
            name='DiskUsage',
        ),
    ]
